### ISSUE TITLE
Is it just me or has the dark mode toggle just disappeared?

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [monashlinks/monashlinks.github.io#3]
Per title. My PC is stuck in dark mode while phone in light mode

![image](https://user-images.githubusercontent.com/49895442/62266027-f6ff4100-b469-11e9-8427-bbbaa94efd02.png)

**Comment by theKKCD** [comment]
Hi, so [epetousis](https://github.com/epetousis), who manages the Jekyll theme for this and other link directories, has updated the theme such that the site will automatically choose a light or dark theme based on the user’s current theme preference in their OS (using dark mode or light mode). 

More info: https://github.com/epetousis/link-directory/pull/1

Please feel free to open an issue there. If there is support to add the toggle back in, I’d be open to sorting something out with him.
